#!/usr/bin/env python
Import(["env", "is_linux", "compiler", "defines",
  "cpp_flags", "ld_flags"])

platform_dir = "windows"
if (is_linux):
  platform_dir = "linux"
plugin_out = "../../bin/plugins/" + platform_dir + "/free/"

modules = [
  "../../modules/itlib/include",
  ".",
  "..",
  "../..", # for plugin-api
]
src_dir = "../"

def make_shared_lib(name, sources):
  env.SharedLibrary(
    target = plugin_out + name,
    source = sources,
    CXX = compiler,
    CPPDEFINES = defines,
    LINKFLAGS = ld_flags,
    CXXFLAGS = cpp_flags,
    CPPPATH = modules
  )

make_shared_lib("invert", "invert/invert.c")

make_shared_lib("colorop", [
  "colorop/colorop.cpp",
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "utils/random.cpp",
  src_dir + "utils/aalloc.cpp",
])

make_shared_lib("pixelsort", [
  "pixelsort/pixelsort.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/cmd-parser.cpp",
])

make_shared_lib("lineswap", [
  "lineswap/lineswap.cpp",
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "utils/random.cpp",
])

make_shared_lib("average", [
  "frame-average/frame-average.cpp",
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
])

make_shared_lib("tvsim", [
  Glob("tvsim/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/random.cpp",
])

make_shared_lib("stars", [
  Glob("stars/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/random.cpp",
])

make_shared_lib("rdither", [
  Glob("rdither/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/random.cpp",
])

make_shared_lib("shatter", [
  Glob("shatter/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/random.cpp",
])

make_shared_lib("3d-denoise", [
  Glob("3d-denoise/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/log.cpp",
])

'''
пока не могу добавить это
make_shared_lib("stabilyzer", [
  Glob("stabilyzer/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/log.cpp",
])
'''

make_shared_lib("gigascreen", [
  Glob("gigascreen/*.cpp"),
  src_dir + "utils/cmd-parser.cpp",
  src_dir + "image/image.cpp",
  src_dir + "image/color.cpp",
  src_dir + "utils/aalloc.cpp",
  src_dir + "utils/log.cpp",
])
