#!/usr/bin/env python
Import(["env", "cxx", "cpp_flags", "is_linux", "defines", "ld_flags"])
sources = [
  Glob("*.cpp"),
  Glob("utils/*.cpp"),
  Glob("video/*.cpp"),
  Glob("image/*.cpp"),
  Glob("plugins/*.cpp"),
]
inc_path = [
  "../modules/DyLib",
  #"../modules/RPI",
  ".", # src
]
lib_path = []
used_libs = [
  #"pthread",
  #"m",
  "avcodec",
  "avfilter",
  "avformat",
  "avutil",
  "swscale",
]
thirdparty_path = "../thirdparty/"
bin_path = "../bin/"

if (is_linux):
  used_libs.extend(["pthread", "m", "SDL2", "dl"])
else:
  used_libs.extend(["mingw32", "SDL2main", "SDL2"])
  inc_path.extend([
    thirdparty_path + "DyLib",
    thirdparty_path + "ffmpeg/include",
    thirdparty_path + "SDL2/include",
  ])
  lib_path.extend([
    thirdparty_path + "SDL2/lib",
    thirdparty_path + "ffmpeg/lib",
  ])

env.Program(
  target = bin_path + "seze",
  source = sources,
  CXX = cxx,
  CXXFLAGS = cpp_flags,
  LIBPATH = lib_path,
  CPPPATH = inc_path,
  LINKFLAGS = ld_flags,
  LIBS = used_libs,
  CPPDEFINES = defines,
)
